# Generated by Django 3.2.7 on 2021-10-06 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, max_length=2000, null=True)),
                ('id_productos', models.ManyToManyField(to='back.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('direc_maquina', models.TextField(blank=True, max_length=80, null=True, verbose_name='direccion maquina')),
                ('is_activate', models.BooleanField(default=False, verbose_name='maquina activa')),
                ('id_ordenes_maquina', models.ManyToManyField(to='back.Orden')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.cliente')),
            ],
        ),
    ]
