# Generated by Django 3.2.7 on 2021-10-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_maquina_orden_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False, verbose_name='id cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField(verbose_name='telefono')),
                ('asesoria', models.CharField(choices=[('Informacion', 'Informacion'), ('Instalacion', 'Instalacion'), ('Quejas y reclamos', 'Quejas y reclamos')], max_length=50, verbose_name='asesoria')),
                ('comentario', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
    ]
